#!/usr/bin/env python3
"""Generate a packaged offline viewer from actual reference executions."""
import json
from pathlib import Path
from undoscope.demo import SCENARIOS, run
ROOT=Path(__file__).resolve().parents[1]
data={name:run(name) for name in SCENARIOS}
raw=json.dumps(data).replace('</','<\\/')
html=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UndoScope | Recovery security lab</title>
<style>
:root{--ink:#14263d;--muted:#617083;--line:#d9e1e5;--teal:#087c71;--red:#b84d3e;--paper:#f4f5f1}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,-apple-system,sans-serif}header{background:#13283e;color:#fff;padding:22px 6%;display:flex;justify-content:space-between;align-items:center}header b{letter-spacing:.03em;font-size:23px}header a{color:#d4e9e6;text-decoration:none;margin-left:22px;font-size:14px}main{max-width:1160px;margin:42px auto;padding:0 28px}.eyebrow{color:var(--teal);font-size:12px;font-weight:750;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(35px,4.5vw,58px);line-height:1.13;letter-spacing:-.04em;margin:12px 0 18px;max-width:800px}h2{font-size:21px;margin:0 0 10px}p{max-width:850px;color:var(--muted)}.lede{font-size:19px;max-width:760px}.meta{font-size:12px;color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:32px 0}.metric,.panel{background:#fff;border:1px solid var(--line);border-radius:10px;padding:23px}.metric strong{display:block;font-size:28px;line-height:1.2}.metric span{font-size:13px;color:var(--muted)}.controls{display:flex;gap:20px;align-items:end;flex-wrap:wrap;margin:24px 0 18px}label{font-size:12px;font-weight:650;text-transform:uppercase;letter-spacing:.05em}select{display:block;margin-top:6px;padding:11px 34px 11px 12px;border:1px solid #b8c6ce;border-radius:5px;font-size:14px;background:#fff;color:var(--ink);min-width:240px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:22px 0}.tag{font-size:11px;letter-spacing:.06em;text-transform:uppercase;font-weight:750}.bad{color:var(--red)}.good{color:var(--teal)}.outcome{display:inline-block;border-radius:4px;padding:4px 9px;background:#eff3f4;font-size:12px;font-family:ui-monospace,monospace}.rows{margin-top:22px}.row{display:flex;justify-content:space-between;gap:15px;border-bottom:1px solid #edf0f2;padding:9px 0;font-size:14px}.row span{color:var(--muted)}.row b{text-align:right;max-width:65%;overflow-wrap:anywhere}.caption{font-size:13px;margin:14px 0 0}.command{background:#152a40;color:#dcf4ee;border-radius:8px;padding:18px;overflow:auto;font:13px/1.7 ui-monospace,monospace;white-space:pre-wrap}.note{padding:18px 22px;border-left:3px solid var(--teal);background:#eaf2ef;font-size:14px;margin:28px 0}.note p{margin:0;color:#354f59}details{font-size:13px;margin-top:22px}pre{max-height:280px;overflow:auto;font-size:11px}footer{margin:42px 0;color:var(--muted);font-size:12px}.evidence{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:28px 0}.evidence img{width:100%;border:1px solid var(--line);border-radius:6px}a{color:var(--teal)}@media(max-width:700px){.cards,.metrics,.evidence{grid-template-columns:1fr}header{align-items:start}header nav{display:none}main{padding:0 18px}.metric{padding:15px}}
</style>
<header><b>UndoScope<span style="color:#77c6b8">.</span></b><nav><a href="#lab">Recovery lab</a><a href="#evidence">Evidence</a><a href="../output/pdf/undoscope-paper.pdf">Technical paper ↗</a></nav></header>
<main><div class="eyebrow">Agent security · Reproducible research</div><h1>Undo only what<br>your workflow owns.</h1><p class="lede">The right receipt can still trigger the wrong inverse. Explore what happens when another actor changes state before an agent tries to recover.</p><div class="meta">Shivam Gupta · Technical report and reference implementation · September 2026</div>
<div class="metrics"><div class="metric"><strong>1,364</strong><span>bounded histories, seven recovery policies</span></div><div class="metric"><strong>240</strong><span>live model tasks, 720 API responses</span></div><div class="metric"><strong>90</strong><span>persistent crash and concurrency schedules</span></div></div>
<section id="lab"><div class="eyebrow">Offline replay lab</div><h2>One failure. Two recovery paths.</h2><div class="controls"><label>Scenario<select id="scenario"><option value="shared-grant">Two owners, one permission</option><option value="same-value">The same-value update</option><option value="disjoint-change">An unrelated note survives</option><option value="name-reuse">A name is reused</option></select></label><label>Compare against<select id="policy"><option value="mapped">Mapped inverse</option><option value="value">Value guard</option><option value="snapshot">Snapshot restore</option><option value="object">Object-version guard</option><option value="field">Component guard</option></select></label></div><p id="description"></p><div class="cards" id="cards"></div><p class="caption">These panels replay traces generated by the real local adapter. To execute the operations live, run the command below. The viewer makes no API calls.</p><div id="command" class="command"></div><details><summary>Inspect the recorded state and provenance</summary><pre id="trace"></pre></details></section>
<div class="note"><p><b>The boundary:</b> the model supplies a receipt identifier. A trusted host binds identity. A typed adapter checks current authority, incarnation, and effect evidence inside the same transaction as the inverse.</p></div>
<section id="evidence"><h2>Read both safety and recovery coverage.</h2><p>Zero mutations alone is not enough: deny-all also meets that test. The benchmark reports collateral changes and completed eligible recoveries separately.</p><div class="evidence"><div><img src="../paper/figures/01-safety-recovery.png" alt="Safety and eligible recovery tradeoffs across seven controls"></div><div><img src="../paper/figures/02-domain-results.png" alt="Per-domain collateral and recovery percentages"></div></div><p class="caption">The grammar deliberately stresses interference. These counts describe controlled coverage, not production incidence. The guarantees require trusted adapters, complete provenance, atomic local writes, and independent peer effects.</p></section>
<footer>Code and full data: <a href="https://github.com/shi1720/undoscope">github.com/shi1720/undoscope</a> · <a href="../protocol/literature-review.md">Literature and novelty audit</a><br>Built on established compensation, selective undo, and provenance techniques. Reference implementation; no universal rollback claim.</footer></main>
<script>const DATA=__DATA__;
const names={mapped:'Mapped inverse',value:'Value guard',snapshot:'Snapshot restore',object:'Object guard',field:'Component guard',undoscope:'UndoScope'};
function text(v){return v===null?'resource absent':String(v)}
function update(){const scenario=document.getElementById('scenario').value,policy=document.getElementById('policy').value,d=DATA[scenario];document.getElementById('description').textContent=d.description;const selected=[d.results.find(x=>x.policy===policy),d.results.find(x=>x.policy==='undoscope')];const parent=document.getElementById('cards');parent.replaceChildren();for(const r of selected){const card=document.createElement('div');card.className='panel';const tag=document.createElement('div');tag.className='tag '+(r.policy==='undoscope'?'good':'bad');tag.textContent=r.policy==='undoscope'?'Effect-scoped recovery':'Comparator';card.append(tag);const title=document.createElement('h2');title.textContent=names[r.policy];card.append(title);const status=document.createElement('span');status.className='outcome';status.textContent=r.result.status;card.append(status);const rows=document.createElement('div');rows.className='rows';const a=r.after,b=r.before,raw=r.raw_after;const pairs=[['Resource',a?'present':'absent'],['Ticket status',a?.fields.status??'—'],['Note',a?.fields.note??'—'],['Effective members',a?.members.join(', ')||'none'],['Active grant contributions',raw?Object.keys(raw.grants).length:0],['Balance',a?.balance??'—']];for(const [k,v] of pairs){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=k;const val=document.createElement('b');val.textContent=text(v);row.append(label,val);rows.append(row)}card.append(rows);parent.append(card)}document.getElementById('trace').textContent=JSON.stringify(selected,null,2);document.getElementById('command').textContent='uv run undoscope-demo --scenario '+scenario+'\nuv run pytest -q';}
document.getElementById('scenario').addEventListener('change',update);document.getElementById('policy').addEventListener('change',update);update();</script></html>'''
(ROOT/'demo/index.html').write_text(html.replace('__DATA__',raw))
(ROOT/'demo/traces.json').write_text(json.dumps(data,indent=2))
print('Generated offline viewer from',len(data),'executed scenarios.')
